[package]
name = "trivia"
version = "0.1.0"
authors = ["Johan Burell <johan.burell@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
askama = "0.7"
bytes = "*"
env_logger = "0.5"
futures = "*"
log = "0.4.5"
reqwest = "0.9.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ws = "*"
